"""add coluna nome na tabela usuarios

Revision ID: ce664bb4b16a
Revises: d76eff74b73b
Create Date: 2026-05-08 15:54:20.552814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce664bb4b16a'
down_revision: Union[str, Sequence[str], None] = 'd76eff74b73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
